### ISSUE TITLE
"make run" errors

### ISSUE THREAD

**Issue by Ironlenny** [turtl/desktop#52]
I'm on Kubuntu 16.04. I get the following errors when I run "make run"

````
$ make run
/opt/nwjs-v0.16.1-linux-x64/nw .
Error: unrecognized flag --harmony_proxies
Try --help for options
chrome-extension://lbmpdaokhedfkjnleihfpnemckinodnf/data/app/config/auth.js:3
config.auth = [
^

ReferenceError: config is not defined
    at chrome-extension://lbmpdaokhedfkjnleihfpnemckinodnf/data/app/config/auth.js:3:1
chrome-extension://lbmpdaokhedfkjnleihfpnemckinodnf/data/app/config/routes.js:1
config.routes = {
^

ReferenceError: config is not defined
    at chrome-extension://lbmpdaokhedfkjnleihfpnemckinodnf/data/app/config/routes.js:1:1
chrome-extension://lbmpdaokhedfkjnleihfpnemckinodnf/data/app/turtl/setup.js:7
        if(new String(config.client) == 'desktop')
                      ^

ReferenceError: config is not defined
    at chrome-extension://lbmpdaokhedfkjnleihfpnemckinodnf/data/app/turtl/setup.js:7:16
chrome-extension://lbmpdaokhedfkjnleihfpnemckinodnf/data/controllers/add_note.js:1
var AddNoteController = OpenNoteController.extend({
                        ^

ReferenceError: OpenNoteController is not defined
    at chrome-extension://lbmpdaokhedfkjnleihfpnemckinodnf/data/controllers/add_note.js:1:25
chrome-extension://lbmpdaokhedfkjnleihfpnemckinodnf/data/controllers/bookmark.js:1
var BookmarkController = OpenNoteController.extend({
                         ^

ReferenceError: OpenNoteController is not defined
    at chrome-extension://lbmpdaokhedfkjnleihfpnemckinodnf/data/controllers/bookmark.js:1:26
````

A window appears with the menu bar, but I can not interact with it, and no login prompt is shown.

**Comment by CoderDimi** [comment]
Same issue on Ubuntu here.

**Comment by leolivier** [comment]
Same for me on Linux Mint

**Comment by Hodapp87** [comment]
Similar for me on NixOS; it complains about `--harmony_collections` regardless of what Node version I use.

**Comment by ripatte** [comment]
I can confirm this on Ubuntu 16.04 too.

**Comment by sadmansk** [comment]
Yeap, it looks like it has been broken for quiet sometime. Can confirm this on Arch Linux.

**Comment by leolivier** [comment]
I'm afraid turtle is not maintained any more. The last fix is 9 months old...

**Comment by sadmansk** [comment]
Looks like development has moved to the rust rewrite of the app: https://github.com/turtl/core-rs
